aws:
    access_key: access-key
    secret_key: secret-key
    
datasets:
    - name: weather
      bucket-name: happy-cow-weather
      local-target-folder: './data/raw/weather/'
    - name: milk-volumes
      bucket-name: happy-cow-milk-volumes
      local-target-folder: ./data/raw/milk-volumes/
    - name: classifications
      bucket-name: happy-cow-classifications
      local-target-folder: ./data/raw/classifications/